### ISSUE TITLE
Login 'Failure'

### ISSUE THREAD

**Issue by The-SamminAter** [Matchstic/ReProvision#139] opened 2020-01-15 17:02 UTC
**Describe the bug**
I get `Failure Your session has expired. Please log in` when trying to log in. I just changed my Apple ID password, as Apple locked my Apple ID, and signed out in ReProvision. The Apple ID has 2FA enabled.
I don't know if this could be a problem, but the password is extremely long.

**To Reproduce**
1. Have 2FA enabled
2. Change your password/have your Apple ID locked and then unlock it
3. Sign out on ReProvision
4. Try to sign into your Apple ID in ReProvision
4. Get error message

**Expected behavior**
ReProvision would sign in properly

**Screenshots**
![ReProvisionError](https://user-images.githubusercontent.com/48739810/72453901-b758b700-3774-11ea-812b-4a09f0c2b8c5.png)

**Device (please complete the following information):**
- iOS 10.3.3
- iPhone 6s
- ReProvision 0.5~release
- The dark mode is from Eclipse 4

**Comment by isja693** [comment] 2020-01-15 17:26
Same issue, it started sometime yesterday

**Comment by isja693** [comment] 2020-01-15 17:27
Also, I did not change my apple id, happening on 3 different devices

**Comment by narwhaldc** [comment] 2020-01-15 19:21
Same issue.  LOOKS to me to be a change in how Apple does logins.  No matter what, if I go to appleid.apple.com and sign in w/ a NON-2factor account, I get asked for two of my three security Q's.  I tried with a 2 factor account, that fails in the same way in ReProvision, but does do the normal thing in a MacOS browser.  SUCKS as now I'm 5 days away from having to find a signing service for unc0ver :(

Fails on my 12.4 iPhoneX with unc0ver AND on a 10.3.4 iPhone 5 with helix.

**Comment by DeafEyeJedi** [comment] 2020-01-16 01:47
Here we go again... Ive been getting 'updateCurrentTeamIDWithComplettionHandler: No Team ID present! This is *really bad*.' message.
    On Wednesday, January 15, 2020, 11:21:25 AM PST, Tony <notifications@github.com> wrote:  
 
 
Same issue. LOOKS to me to be a change in how Apple does logins. No matter what, if I go to appleid.apple.com and sign in w/ a NON-2factor account, I get asked for two of my three security Q's. I tried with a 2 factor account, that fails in the same way in ReProvision, but does do the normal thing in a MacOS browser. SUCKS as now I'm 5 days away from having to find a signing service for unc0ver :(

Fails on my 12.4 iPhoneX with unc0ver AND on a 10.3.4 iPhone 5 with helix.

**Comment by Cr4nkSt4r** [comment] 2020-01-16 01:54
Please be patient until the update gets released.

**Comment by Matchstic** [comment] 2020-01-16 22:42
Duplicate of #138

**Closed by Matchstic** 2020-01-16 22:42 UTC
