### ISSUE TITLE
Sign in failure

### ISSUE THREAD

**Issue by lemonthefish** [Matchstic/ReProvision#111] opened 2019-11-25 17:03 UTC
**Describe the bug**
My device with 2FA apple ID logged in through settings is getting the error:
"Failure. Your apple id or password is incorrect. App-specific passwords are not supported."
even with the correct credentials.

**To Reproduce**
Login. Only seems to be affecting some users, not all.

**Expected behavior**
Should be able to login normally.

**Device (please complete the following information):**
Iphone on IOS 12.1

**Comment by sking512** [comment] 2019-11-25 17:13
I got failure code (-22410)
Device
- iOS Version :12.1.2
- Device :iPhoneX

**Comment by Matchstic** [comment] 2019-11-25 17:22
Please update to experimental6-1.

This doesn't fix anything, but adds more context to the error message why the login failed. Should help figure things out.

**Comment by Warrior559** [comment] 2019-11-25 17:25
I’m on the latest version of ReProvision and also get the same thing. Login failure even tho ik using correct password

**Comment by Warrior559** [comment] 2019-11-25 17:26
> Please update to experimental6-1. This doesn't fix anything, but adds more context to the error message why the login failed. Should help figure things out.
> […](#)

Will the login failure be fixed?

**Comment by lemonthefish** [comment] 2019-11-25 17:29
![596F7782-7BA1-4C18-9840-4EDB77B74FD4](https://user-images.githubusercontent.com/58183448/69563497-37d21700-0f7f-11ea-86fb-c94071b24a58.jpeg)
![0174B4B6-ABDC-4021-8591-47A443E8C595](https://user-images.githubusercontent.com/58183448/69563499-386aad80-0f7f-11ea-85f2-6164b7da1ce6.jpeg)

**Comment by Warrior559** [comment] 2019-11-25 17:33
Yep just updated to 6.1 and still the login failure issue.

**Comment by sking512** [comment] 2019-11-25 17:54
Description error
-I use the basic Apple login method, I tried to update 0.5~experimental6-1, but this problem occurred after 0.5 ~ experimental1.
Expected behavior
-This problem occurs after 0.5~experimental1.
Device
- Device：iPhoneX 12.1.2 rootless
![1574703813236](https://user-images.githubusercontent.com/57693254/69564625-4d325a00-0fee-11ea-89d1-62fffa4020b2.jpg)

**Comment by DiabloQa** [comment] 2019-11-25 18:09
The failure happen only on (hotmail) if you try (gmail, outlook, etc..) you will be able to log in

I just tried 20 different emails and that’s what I figured out

**Comment by Matchstic** [comment] 2019-11-25 18:27
Is anyone using a paid developer account? Curious to see if that affects anything!

**Comment by lemonthefish** [comment] 2019-11-25 18:42
Im using a non-paid apple account with gmail. I don't think this only affects hotmail.

**Comment by avdimdv** [comment] 2019-11-25 22:00
Same login failure. On several accounts, some without F2A. Passwords do contain lower and upper letters and digits.

**Comment by Matchstic** [comment] 2019-11-25 22:02
What region are your accounts in? Eg, are they US, UK, etc for the App Store?

**Comment by Matchstic** [comment] 2019-11-25 22:08
Additionally:

1. Does anyone’s account have 2FA enabled?
2. Does anyone’s account have a capital letter in your username (eg, email address)?

**Comment by avdimdv** [comment] 2019-11-25 22:17
3 different - DE,US,RU
No F2A
No capital in e-mail.

And I can't pass login screen to manage certificates etc.

**Comment by nate-moo** [comment] 2019-11-25 22:22
How come I don’t see experimental 6-1? I only see experimental 4

**Comment by CHristophrP** [comment] 2019-11-26 00:44
Matchstic, thanks for all the work.
Signed up to Github to contribute. 

Experiencing Failure trying to sign into ReProvision 6-1 using 3 different ID’s.
From UK, CAN, & US.
Non with 2FA

Only use it for unc0ver. 

TIA

**Comment by Scunkaneli** [comment] 2019-11-26 19:46
I've got this error when using an email that contained upper-case letters, lower-case letters and numbers. I changed the upper-case letters to lower-case and was able to log in successfully!

**Comment by CHristophrP** [comment] 2019-11-26 22:31
The email i use doesn’t have the lower-case issue. Still fails unfortunately 

Thx for the suggestion tho

**Comment by Matchstic** [comment] 2019-11-27 01:06
I’ve had a really useful log sent in that explains the issue. Will work on it when I can, but right now that’s a small amount of time immediately after work.

**Comment by CHristophrP** [comment] 2019-11-27 02:11
Sounds great Matt 👌
Most appreciated

**Comment by Matchstic** [comment] 2019-11-27 17:05
This should now be fixed with version 0.5~experimental7. Please confirm if that's the case.

**Comment by Scunkaneli** [comment] 2019-11-27 17:16
Same error for me. Signing in works as soon as I change the upper case 
letters to lower case.

**Comment by avdimdv** [comment] 2019-11-27 17:32
For me 0.5~experimental7 works fine. I was able to log in and resign unc0ver.
Thank you, otherwise I will be forced to go IOS App Signer route on macOS in VM in case I will need reboot the phone.

**Comment by CHristophrP** [comment] 2019-11-27 19:27
> This should now be fixed with version 0.5~experimental7. Please confirm if that's the case.

Matt, all is now fixed here with this new update.
Updated, signed in with my usual UK appleID/password & was able to sign unc0ver no problem.

Thanks again

**Comment by Warrior559** [comment] 2019-11-27 20:54
![723E0978-D9DB-4DA9-8DE5-29955BF96CA1](https://user-images.githubusercontent.com/58185073/69758637-e6f42700-1114-11ea-9d72-b0266f84d9cc.png)

Matt, after new update on Nov 27 I’m still having logging failure issue I hope this gets resolved I depend on ReProvision a lot thank you.

**Comment by Warrior559** [comment] 2019-11-27 20:55
![73DA9319-D68D-4416-B036-DCB11E55BC61](https://user-images.githubusercontent.com/58185073/69758715-20c52d80-1115-11ea-8747-bf3784a5050f.png)

Matt, after new update on Nov 27 I’m still having logging failure issue I hope this gets resolved I depend on ReProvision a lot thank you.

**Comment by Scunkaneli** [comment] 2019-11-27 20:57
Try to change the V and T in your email to v and t, ie. make them 
lowercase. This workaround works for me

**Comment by Warrior559** [comment] 2019-11-27 21:01
Thanks will try

**Comment by Warrior559** [comment] 2019-11-27 21:02
How would I be able to? I don’t think I can edit a iCloud acc

**Comment by Scunkaneli** [comment] 2019-11-27 21:12
Just type your email lowercase into the username field in ReProvision, you 
do not need to change the actual email. Maybe it works for you too

**Comment by Warrior559** [comment] 2019-11-27 21:56
Holy shit it worked thanks

**Comment by s2339956** [comment] 2019-11-28 07:08
My e-mail was tinhsieh@gamania.com I encountered the same problem with the new version and was once available

**Comment by Matchstic** [comment] 2019-11-28 16:37
All usernames are now automatically sent as lowercase to Apple with v0.5~experimental8

**Comment by DeafEyeJedi** [comment] 2019-11-28 17:38
Excellent work, Matt! ;)

**Comment by Scunkaneli** [comment] 2019-11-29 12:39
v0.5~experimental8 fixed the issue for me. Thank you!

**Closed** 2019-12-11 16:30 UTC
